<?php 

$africa = array(
   "Algeria",
   "Angola",
   "Benin",
   "Botswana",
   "Burkina Faso",
   "Burundi",
   "Cabo Verde",
   "Cameroon",
   "Central African Republic",
   "Chad",
   "Comoros",
   "Democratic Republic of the Congo",
   "Congo",
   "Cote d'Ivoire",
   "Djibouti",
   "Egypt",
   "Equatorial Guinea",
   "Eritrea",
   "Eswatini",
   "Ethiopia",
   "Gabon",
   "Gambia",
   "Ghana",
   "Guinea",
   "Guinea-Bissau",
   "Kenya",
   "Lesotho",
   "Liberia",
   "Libya",
   "Madagascar",
   "Malawi",
   "Mali",
   "Mauritania",
   "Mauritius",
   "Morocco",
   "Mozambique",  
   "Namibia",
   "Niger",
   "Nigeria",
   "Rwanda",
   "Sao Tome and Principe",
   "Senegal",
   "Seychelles",
   "Sierra Leone",
   "Somalia",
   "South Africa",
   "South Sudan",
   "Sudan",
   "Tanzania",
   "Togo",
   "Tunisia",
   "Uganda",
   "Zambia",
   "Zimbabwe",
);

$latinAmerica = array(
    "Argentina", 
    "Bolivia", 
    "Brazil", 
    "Costa Rica",
    "Chile",
    "Colombia",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "French Guiana",
    "Guadeloupe",
    "Guatemala", 
    "Haiti",
    "Honduras",
    "Martinique",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Puerto Rico",
    "Saint Barthelemy",
    "Saint Martin",
    "Uruguay",
    "Venezuela",
);

$caribbean = array(
    "Anguilla", 
    "Antigua and Barbuda",
    "Aruba", 
    "Bahamas", 
    "Barbados",
    "British Virgin Islands",
    "Cayman Islands",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Guadeloupe",
    "Haiti",
    "Jamaica",
    "Martinique", 
    "Montserrat",
    "Puerto Rico",
    "Saint Barthélemy",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
);

$southeastAsia = array(
    "Brunei", 
    "Myanmar",
    "Cambodia",    
    "Indonesia",
    "Laos",
    "Malaysia",
    "Philippines",
    "Singapore",
    "Thailand",
    "Timor-Leste",
    "Vietnam",
);

$pacific = array(
    "Cook Islands", 
    "Fiji",
    "Kiribati",    
    "Marshall Islands",
    "Micronesia",
    "Nauru",
    "Niue",
    "Palau",
    "Papua New Guinea",
    "Samoa",
    "Solomon Islands",
    "Tonga",
    "Tuvalu",
    "Vanuatu",
);

$westernHemisphere = array(
    "Anguilla", 
    "Antigua and Barbuda",
    "Argentina",
    "Aruba",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bermuda",
    "Bolivia",
    "Brazil",
    "British Virgin Islands",
    "Canada",
    "Cayman Islands",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "French Guiana",
    "Grenada",
    "Guadeloupe",
    "Guatemala",
    "Guyana",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Mexico",
    "Montserrat",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Saint Barthelemy",
    "Saint Kitts & Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Suriname",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
    "USA",
    "Uruguay",
    "Venezuela" 
   );

$asia = array(
  "Afghanistan",
  "Azerbaijan", 
  "Bahrain", 
  "Bangladesh", 
  "Bhutan", 
  "Brunei", 
  "Cambodia", 
  "China", 
  "Cyprus", 
  "Georgia",
  "India", 
  "Indonesia", 
  "Iran", 
  "Iraq", 
  "Israel", 
  "Japan", 
  "Jordan", 
  "Kazakhstan", 
  "Kuwait", 
  "Kyrgyzstan", 
  "Laos", 
  "Lebanon", 
  "Malaysia", 
  "Maldives", 
  "Mongolia", 
  "Myanmar", 
  "Nepal", 
  "North Korea", 
  "Oman", 
  "Pakistan", 
  "Palestine State", 
  "Philippines", 
  "Qatar", 
  "Saudi Arabia", 
  "Singapore", 
  "South Korea", 
  "Sri Lanka", 
  "Syria", 
  "Taiwan", 
  "Tajikistan", 
  "Thailand", 
  "Timor-Leste", 
  "Turkey", 
  "Turkmenistan", 
  "United Arab Emirates", 
  "Uzbekistan",
  "Vietnam", 
  "Yemen"
  );
 
 $EuropeanUnion = array(
	"Austria",
	"Belgium",
	"Bulgaria",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Estonia",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Hungary",
	"Ireland",
	"Italy",
	"Latvia",
	"Lithuania",
	"Luxembourg",
	"Malta",
	"Netherlands",
	"Poland",
	"Portugal",
	"Romania",
	"Slovakia",
	"Slovenia",
	"Spain",
	"Sweden",
	);

$EuropeanEconomicArea = array(
	"Austria",
	"Belgium",
	"Bulgaria",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Estonia",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Hungary",
	"Ireland",
	"Italy",
	"Latvia",
	"Lithuania",
	"Luxembourg",
	"Malta",
	"Netherlands",
	"Poland",
	"Portugal",
	"Romania",
	"Slovakia",
	"Slovenia",
	"Spain",
	"Sweden",
	"Iceland",
	"Liechtenstein",
	"Norway",
	);
	
	
 
$Europe = array(
	"Albania",
	"Andorra",
	"Austria",
	"Belarus",
	"Belgium",
	"Bosnia and Herzegovina",
	"Bulgaria",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Estonia",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Holy See",
	"Hungary",
	"Iceland",
	"Ireland",
	"Italy",
	"Latvia",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Malta",
	"Moldova",
	"Monaco",
	"Montenegro",
	"Netherlands",
	"North Macedonia",
	"Norway", 
	"Poland",
	"Portugal",
	"Romania",
	"Russia",
	"San Marino",
	"Serbia",
	"Slovakia",
	"Slovenia",
	"Spain",
	"Sweden",
	"Switzerland",
	"Ukraine",
	"United Kingdom",
	
	);


$northAmerica_list = array(
    "Antigua and Barbuda", 
    "Bahamas", 
    "Barbados",
    "Belize",
    "Canada", 
    "Costa Rica", 
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "El Salvador", 
    "Grenada", 
    "Guatemala", 
    "Haiti", 
    "Honduras", 
    "Jamaica", 
    "Mexico", 
    "Nicaragua", 
    "Panama", 
    "Saint Kitts and Nevis", 
    "Saint Lucia", 
    "Saint Vincent and the Grenadines", 
    "Trinidad and Tobago",
    "United States" );

$oceania_list = array(
    "Australia", 
    "Fiji",
    "Kiribati", 
    "Marshall Islands", 
    "Micronesia", 
    "Nauru",
    "New Zealand", 
    "Palau", 
    "Papua New Guinea", 
    "Samoa", 
    "Solomon Islands", 
    "Tonga",
    "Tuvalu",
    "Vanuatu");

$middleEast_list = array(
    "Bahrain",
    "Iran",
    "Iraq",
    "Israel", 
    "Jordan",
    "Kuwait",
    "Lebanon",
    "Oman",
    "Palestine",
    "Qatar",
    "Saudi Arabia",
    "Syria",
    "Turkey",
    "United Arab Emirates",
    "Yemen",
    "Egypt",
    "Cyprus");
    
    $commonwealth_list = array(
        "Antigua and Barbuda",
         "Australia",
         "Bahamas",
         "Bangladesh",
         "Barbados",
         "Belize",
         "Botswana", 
        "Brunei Darussalam", 
        "Cameroon",
         "Canada", 
        "Cyprus", 
        "Dominica",
         "Eswatini",
         "Fiji Islands",
         "Gabon",
         "Gambia",
        "Ghana", 
        "Grenada",
         "Guyana", 
        "India", 
        "Jamaica", 
        "Kenya",
         "Kiribati",
         "Lesotho", 
        "Malawi", 
        "Malaysia",
         "Maldives",
         "Malta",
         "Mauritius",
         "Mozambique",
         "Namibia",
         "Nauru",
         "New Zealand",
         "Nigeria",
         "Pakistan",
         "Papua New Guinea",
         "Rwanda",
         "Samoa",
         "Seychelles", 
        "Sierra Leone",
         "Singapore",
         "Solomon Islands",
         "South Africa",
         "Sri Lanka",
         "St Kitts and Nevis",
         "St Lucia",
         "St Vincent and the Grenadines",
         "Tanzania",
         "Togo",
         "Tonga",
         "Trinidad and Tobago",
         "Tuvalu",
         "Uganda",
         "Vanuatu",
         "Zambia"
        );


    $southAsia_list = array(
   "Afghanistan",
   "Bangladesh",
   "Bhutan",
   "India",
   "Maldives",
   "Nepal",
   "Pakistan",
   "Sri Lanka",
 );

  $eastAsia_list = array(
  "China", 
  "Hong Kong", 
  "Japan",
  "Macau",
  "Mongolia",
  "North Korea", 
  "South Korea", 
  "Taiwan",
  );

        
	

?>