<?php 

$All_Countries_Array = array(
    'All Countries' => array(
        'Afghanistan',
        'Aland Islands',
        'Albania',
        'Algeria',
        'American Samoa',
        'Andorra',
        'Angola',
        'Anguilla',
        'Antarctica',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Bouvet Island',
        'Brazil',
        'British Virgin Islands',
        'Brunei',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Cabo Verde',
        'Cayman Islands',
        'Central African Republic',
        'Chad',
        'Chile',
        'China',
        'Christmas Island',
        'Cocos Islands',
        'Colombia',
        'Comoros',
        'Democratic Republic of the Congo',
        'Congo',
        'Cook Islands',
        'Costa Rica',
        'Cote d\'Ivoire',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Ethiopia',
        'Eswatini',
        'Faroe Islands',
        'Falkland Islands',
        'Fiji',
        'Finland',
        'France',
        'French Guiana',
        'French Polynesia',
        'French Southern Territories',
        'Gabon',
        'Gambia',
        'Georgia',
        'Germany',
        'Ghana',
        'Gibraltar',
        'Greece',
        'Greenland',
        'Grenada',
        'Guadeloupe',
        'Guam',
        'Guatemala',
        'Guernsey',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Heard Island and McDonald Islands',
        'Holy See',
        'Honduras',
        'Hong Kong',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Isle of Man',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jersey',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macao',
        'Macedonia',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Martinique',
        'Mauritania',
        'Mauritius',
        'Mayotte',
        'Mexico',
        'Micronesia',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Montserrat',
        'Morocco',
        'Mozambique',
        'Myanmar',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands Antilles',
        'Netherlands',
        'New Caledonia',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'North Korea',
        'North Macedonia',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine State',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Pitcairn Islands',
        'Poland',
        'Portugal',
        'Puerto Rico',
        'Qatar',
        'Reunion',
        'Romania',
        'Russia',
        'Rwanda',
        'Saint Barthelemy',
        'Saint Helena',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin',
        'Saint Pierre and Miquelon',
        'Saint Vincent and the Grenadines',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'South Georgia and the South Sandwich Islands',
        'South Korea',
        'South Sudan',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Svalbard and Jan Mayen Islands',
        'Sweden',
        'Switzerland',
        'Syria',
        'Tajikistan',
        'Tanzania',
        'Taiwan',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tokelau',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Turks and Caicos Islands',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'USA',
        'United States Minor Outlying Islands',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Venezuela',
        'Vietnam',
        'Wallis and Futuna',
        'Western Sahara',
        'Yemen',
        'Zambia',
        'Zimbabwe',
    ),
    'Tier1' => array(
        'Andorra',
        'Armenia',
        'Australia',
        'Austria',
        'Belarus',
        'Belgium',
        'Bosnia and Herzegovina',
        'Bulgaria',
        'Canada',
        'China',
        'Croatia',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Finland',
        'France',
        'Georgia',
        'Germany',
        'Greece',
        'Greenland',
        'Holy See',
        'Hungary',
        'Iceland',
        'Ireland',
        'Italy',
        'South Korea',
        'Luxembourg',
        'Netherlands',
        'New Zealand',
        'Norway',
        'Poland',
        'Portugal',
        'Romania',
        'Serbia',
        'Slovakia',
        'Slovenia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Ukraine',
        'United Kingdom',
        'USA',
    ),
    'Tier2' => array(
        'Aland Islands',
        'Albania',
        'American Samoa',
        'Antarctica',
        'Antigua and Barbuda',
        'Argentina',
        'Aruba',
        'Azerbaijan',
        'Bahrain',
        'Barbados',
        'Belize',
        'Bolivia',
        'Bouvet Island',
        'Brazil',
        'British Indian Ocean Territory',
        'British Virgin Islands',
        'Cayman Islands',
        'Chile',
        'Christmas Island',
        'Cocos Islands',
        'Colombia',
        'Comoros',
        'Cook Islands',
        'Costa Rica',
        'Cuba',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'El Salvador',
        'Eritrea',
        'Estonia',
        'Faroe Islands',
        'Guam',
        'Hong Kong',
        'Indonesia',
        'Iran',
        'Iraq',
        'Isle of Man',
        'Israel',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kuwait',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Lithuania',
        'Macao',
        'Macedonia',
        'Malaysia',
        'Marshall Islands',
        'Mauritius',
        'Mexico',
        'Micronesia',
        'Myanmar',
        'Nauru',
        'Oman',
        'Palestine State',
        'Panama',
        'Paraguay',
        'Peru',
        'Philippines',
        'Pitcairn Islands',
        'Puerto Rico',
        'Qatar',
        'Russia',
        'Saint Barthelemy',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin',
        'Saint Pierre and Miquelon',
        'Saint Vincent and the Grenadines',
        'Saudi Arabia',
        'Singapore',
        'South Africa',
        'Syria',
        'Taiwan',
        'Thailand',
        'Trinidad and Tobago',
        'Turkey',
        'Turks and Caicos Islands',
        'United Arab Emirates',
        'United States Minor Outlying Islands',
        'United States Virgin Islands',
        'Venezuela',
        'Vietnam',
        'Western Sahara',
        'Yemen',
    ),
    'Tier3' => array(
        'Afghanistan',
        'Algeria',
        'Angola',
        'Anguilla',
        'Bahamas',
        'Bangladesh',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Botswana',
        'Brunei',
        'Burkina Faso',
        'Burundi',
        'Cambodia',
        'Cameroon',
        'Cabo Verde',
        'Central African Republic',
        'Chad',
        'Democratic Republic of the Congo',
        'Congo',
        'Ivory Coast',
        'Djibouti',
        'Egypt',
        'Equatorial Guinea',
        'Ethiopia',
        'Falkland Islands',
        'Fiji',
        'French Guiana',
        'French Polynesia',
        'French Southern Territories',
        'Gabon',
        'Gambia',
        'Ghana',
        'Gibraltar',
        'Grenada',
        'Guadeloupe',
        'Guatemala',
        'Guernsey',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Heard Island and McDonald Islands',
        'Honduras',
        'India',
        'Jersey',
        'Kazakhstan',
        'Kenya',
        'Kosovo',
        'Kiribati',
        'North Korea',
        'Kyrgyzstan',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Madagascar',
        'Malawi',
        'Maldives',
        'Mali',
        'Malta',
        'Martinique',
        'Mauritania',
        'Mayotte',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Montserrat',
        'Morocco',
        'Mozambique',
        'Namibia',
        'Nepal',
        'Netherlands Antilles',
        'New Caledonia',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'Pakistan',
        'Pacific Region',
        'Palau',
        'Papua New Guinea',
        'Reunion',
        'Rwanda',
        'Saint Helena',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Senegal',
        'Seychelles',
        'Sierra Leone',
        'Solomon Islands',
        'Somalia',
        'South Georgia and the South Sandwich Islands',
        'Sri Lanka',
        'Sudan',
        'South Sudan',
        'Suriname',
        'Svalbard and Jan Mayen Islands',
        'Eswatini',
        'Tajikistan',
        'Tanzania',
        'Timor-Leste',
        'Togo',
        'Tokelau',
        'Tonga',
        'Tunisia',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Wallis and Futuna',
        'Zambia',
        'Zimbabwe',
    ),
    'Africa' => array(
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cameroon",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Democratic Republic of the Congo",
        "Congo",
        "Cote d'Ivoire",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",  
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Sao Tome and Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    ),
    'Latin America' => array(
        "Argentina", 
        "Bolivia", 
        "Brazil", 
        "Costa Rica",
        "Chile",
        "Colombia",
        "Cuba",
        "Dominican Republic",
        "Ecuador",
        "El Salvador",
        "French Guiana",
        "Guadeloupe",
        "Guatemala", 
        "Haiti",
        "Honduras",
        "Martinique",
        "Mexico",
        "Nicaragua",
        "Panama",
        "Paraguay",
        "Peru",
        "Puerto Rico",
        "Saint Barthelemy",
        "Saint Martin",
        "Uruguay",
        "Venezuela",
    ),
    'Caribbean' => array(
        "Anguilla", 
        "Antigua and Barbuda",
        "Aruba", 
        "Bahamas", 
        "Barbados",
        "British Virgin Islands",
        "Cayman Islands",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "Guadeloupe",
        "Haiti",
        "Jamaica",
        "Martinique", 
        "Montserrat",
        "Puerto Rico",
        "Saint Barthélemy",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin",
        "Saint Vincent and the Grenadines",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
    ),
    'Southeast Asia' => array(
        "Brunei", 
        "Myanmar",
        "Cambodia",    
        "Indonesia",
        "Laos",
        "Malaysia",
        "Philippines",
        "Singapore",
        "Thailand",
        "Timor-Leste",
        "Vietnam",
    ),
    'Pacific Island' => array(
        "Cook Islands", 
        "Fiji",
        "Kiribati",    
        "Marshall Islands",
        "Micronesia",
        "Nauru",
        "Niue",
        "Palau",
        "Papua New Guinea",
        "Samoa",
        "Solomon Islands",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
    ),
    'Western Hemisphere' => array(
        "Anguilla", 
        "Antigua and Barbuda",
        "Argentina",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bermuda",
        "Bolivia",
        "Brazil",
        "British Virgin Islands",
        "Canada",
        "Cayman Islands",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "El Salvador",
        "French Guiana",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Guyana",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Mexico",
        "Montserrat",
        "Nicaragua",
        "Panama",
        "Paraguay",
        "Peru",
        "Saint Barthelemy",
        "Saint Kitts & Nevis",
        "Saint Lucia",
        "Saint Martin",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Suriname",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "USA",
        "Uruguay",
        "Venezuela" 
    ),
    'Asia' => array(
        "Afghanistan",
        "Azerbaijan", 
        "Bahrain", 
        "Bangladesh", 
        "Bhutan", 
        "Brunei", 
        "Cambodia", 
        "China", 
        "Cyprus", 
        "Georgia",
        "India", 
        "Indonesia", 
        "Iran", 
        "Iraq", 
        "Israel", 
        "Japan", 
        "Jordan", 
        "Kazakhstan", 
        "Kuwait", 
        "Kyrgyzstan", 
        "Laos", 
        "Lebanon", 
        "Malaysia", 
        "Maldives", 
        "Mongolia", 
        "Myanmar", 
        "Nepal", 
        "North Korea", 
        "Oman", 
        "Pakistan", 
        "Palestine State", 
        "Philippines", 
        "Qatar", 
        "Saudi Arabia", 
        "Singapore", 
        "South Korea", 
        "Sri Lanka", 
        "Syria", 
        "Taiwan", 
        "Tajikistan", 
        "Thailand", 
        "Timor-Leste", 
        "Turkey", 
        "Turkmenistan", 
        "United Arab Emirates", 
        "Uzbekistan",
        "Vietnam", 
        "Yemen"
    ),
    'European Union' => array(
        "Austria",
        "Belgium",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Ireland",
        "Italy",
        "Latvia",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Netherlands",
        "Poland",
        "Portugal",
        "Romania",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
    ),
    'European Economic Area' => array(
        "Austria",
        "Belgium",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Ireland",
        "Italy",
        "Latvia",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Netherlands",
        "Poland",
        "Portugal",
        "Romania",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Iceland",
        "Liechtenstein",
        "Norway",
    ),
    'Europe' => array(
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Holy See",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway", 
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United Kingdom",
    ),

    'Middle East' => array(
        "Bahrain",
        "Cyprus",
        "Egypt",
        "Iran",
        "Iraq",
        "Israel",
        "Jordan",
        "Kuwait",
        "Lebanon",
        "Oman",
        "Palestine State",
        "Qatar",
        "Saudi Arabia",
        "Syria",
        "Turkey",
        "United Arab Emirates",
        "Yemen",
        
    ),    
);

$africa = array(
   "Algeria",
   "Angola",
   "Benin",
   "Botswana",
   "Burkina Faso",
   "Burundi",
   "Cabo Verde",
   "Cameroon",
   "Central African Republic",
   "Chad",
   "Comoros",
   "Democratic Republic of the Congo",
   "Congo",
   "Cote d'Ivoire",
   "Djibouti",
   "Egypt",
   "Equatorial Guinea",
   "Eritrea",
   "Eswatini",
   "Ethiopia",
   "Gabon",
   "Gambia",
   "Ghana",
   "Guinea",
   "Guinea-Bissau",
   "Kenya",
   "Lesotho",
   "Liberia",
   "Libya",
   "Madagascar",
   "Malawi",
   "Mali",
   "Mauritania",
   "Mauritius",
   "Morocco",
   "Mozambique",  
   "Namibia",
   "Niger",
   "Nigeria",
   "Rwanda",
   "Sao Tome and Principe",
   "Senegal",
   "Seychelles",
   "Sierra Leone",
   "Somalia",
   "South Africa",
   "South Sudan",
   "Sudan",
   "Tanzania",
   "Togo",
   "Tunisia",
   "Uganda",
   "Zambia",
   "Zimbabwe",
);

$latinAmerica = array(
    "Argentina", 
    "Bolivia", 
    "Brazil", 
    "Costa Rica",
    "Chile",
    "Colombia",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "French Guiana",
    "Guadeloupe",
    "Guatemala", 
    "Haiti",
    "Honduras",
    "Martinique",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Puerto Rico",
    "Saint Barthelemy",
    "Saint Martin",
    "Uruguay",
    "Venezuela",
);

$caribbean = array(
    "Anguilla", 
    "Antigua and Barbuda",
    "Aruba", 
    "Bahamas", 
    "Barbados",
    "British Virgin Islands",
    "Cayman Islands",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Guadeloupe",
    "Haiti",
    "Jamaica",
    "Martinique", 
    "Montserrat",
    "Puerto Rico",
    "Saint Barthélemy",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
);

$southeastAsia = array(
    "Brunei", 
    "Myanmar",
    "Cambodia",    
    "Indonesia",
    "Laos",
    "Malaysia",
    "Philippines",
    "Singapore",
    "Thailand",
    "Timor-Leste",
    "Vietnam",
);

$pacific = array(
    "Cook Islands", 
    "Fiji",
    "Kiribati",    
    "Marshall Islands",
    "Micronesia",
    "Nauru",
    "Niue",
    "Palau",
    "Papua New Guinea",
    "Samoa",
    "Solomon Islands",
    "Tonga",
    "Tuvalu",
    "Vanuatu",
);

$westernHemisphere = array(
    "Anguilla", 
    "Antigua and Barbuda",
    "Argentina",
    "Aruba",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bermuda",
    "Bolivia",
    "Brazil",
    "British Virgin Islands",
    "Canada",
    "Cayman Islands",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "French Guiana",
    "Grenada",
    "Guadeloupe",
    "Guatemala",
    "Guyana",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Mexico",
    "Montserrat",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Saint Barthelemy",
    "Saint Kitts & Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Suriname",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
    "USA",
    "Uruguay",
    "Venezuela" 
);

$asia = array(
  "Afghanistan",
  "Azerbaijan", 
  "Bahrain", 
  "Bangladesh", 
  "Bhutan", 
  "Brunei", 
  "Cambodia", 
  "China", 
  "Cyprus", 
  "Georgia",
  "India", 
  "Indonesia", 
  "Iran", 
  "Iraq", 
  "Israel", 
  "Japan", 
  "Jordan", 
  "Kazakhstan", 
  "Kuwait", 
  "Kyrgyzstan", 
  "Laos", 
  "Lebanon", 
  "Malaysia", 
  "Maldives", 
  "Mongolia", 
  "Myanmar", 
  "Nepal", 
  "North Korea", 
  "Oman", 
  "Pakistan", 
  "Palestine State", 
  "Philippines", 
  "Qatar", 
  "Saudi Arabia", 
  "Singapore", 
  "South Korea", 
  "Sri Lanka", 
  "Syria", 
  "Taiwan", 
  "Tajikistan", 
  "Thailand", 
  "Timor-Leste", 
  "Turkey", 
  "Turkmenistan", 
  "United Arab Emirates", 
  "Uzbekistan",
  "Vietnam", 
  "Yemen"
);
 
$europeanUnion = array(
	"Austria",
	"Belgium",
	"Bulgaria",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Estonia",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Hungary",
	"Ireland",
	"Italy",
	"Latvia",
	"Lithuania",
	"Luxembourg",
	"Malta",
	"Netherlands",
	"Poland",
	"Portugal",
	"Romania",
	"Slovakia",
	"Slovenia",
	"Spain",
	"Sweden",
);

$europeanEconomicArea = array(
	"Austria",
	"Belgium",
	"Bulgaria",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Estonia",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Hungary",
	"Ireland",
	"Italy",
	"Latvia",
	"Lithuania",
	"Luxembourg",
	"Malta",
	"Netherlands",
	"Poland",
	"Portugal",
	"Romania",
	"Slovakia",
	"Slovenia",
	"Spain",
	"Sweden",
	"Iceland",
	"Liechtenstein",
	"Norway",
);
	
	
 
$europe = array(
	"Albania",
	"Andorra",
	"Austria",
	"Belarus",
	"Belgium",
	"Bosnia and Herzegovina",
	"Bulgaria",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Estonia",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Holy See",
	"Hungary",
	"Iceland",
	"Ireland",
	"Italy",
	"Latvia",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Malta",
	"Moldova",
	"Monaco",
	"Montenegro",
	"Netherlands",
	"North Macedonia",
	"Norway", 
	"Poland",
	"Portugal",
	"Romania",
	"Russia",
	"San Marino",
	"Serbia",
	"Slovakia",
	"Slovenia",
	"Spain",
	"Sweden",
	"Switzerland",
	"Ukraine",
	"United Kingdom",
	
	);

    $MiddleEast = array(
        "Bahrain",
        "Cyprus",
        "Egypt",
        "Iran",
        "Iraq",
        "Israel",
        "Jordan",
        "Kuwait",
        "Lebanon",
        "Oman",
        "Palestine State",
        "Qatar",
        "Saudi Arabia",
        "Syria",
        "Turkey",
        "United Arab Emirates",
        "Yemen",
        
        );

    $All_Countries = array(
        $africa,
        $europe,
        $europeanEconomicArea,
        $europeanUnion,
        $asia,
        $latinAmerica,
        $southeastAsia,
        $caribbean,
        $pacific,
        $westernHemisphere,
        $MiddleEast
    );
	

?>